language: node_js
node_js: node
services:
- mongodb
env:
  matrix:
  - SESSION_SECRET: bippityBoppityB00000
  global:
    secure: l1x7UkgPVqZ6Vbkr4F8iONUevhBwSWBS1Qn5G80tyAvji693ceJqbZjFql8APdE1GpyN3mE1qjeSeB7ENArr2qML7araGiELjmuqFEZuVbLA8JNf+R+Xywqqx7W53phOImqygbk+qhAvFQlw8/yDSv/TLKvn65jdZYWiQS2iKH1nokobnUyIuYUpEujiVCU+G6oZNRV+5CN2sLydIt4H8ccf/EVb8wQn7WM73dQKNgps3wQXyqeAwug5dTZ4vlAWE4O3HlZpPVjUcaJ/1Pgv3pA6HpKMYoeXw+Zip9fb9tnKw2lPprY5EpqiBST05CwiN/0KN0vsBQVgHA5GFpDxWQycIPiDCJatpypcf4hdFa7wxKz7cloJuv+qaABJcKHYHuMhq1xE4PCTa/3hq5UfCHfJ5bEm705fptzakaUWG8SnWtyzryzNjWbJkU29bcUN2ASfUtk5pCojCX0MoSksP9Bzmm4HSJogXalwJ5txUcl5l3OKLn6vK7VNqFmKB0sPxOqMxT4se6dQFbS44M7mmwAwiUq3K5bci4Ga0wL1uYDTdGjDM9tko7b7/pDxUqXFmOqOq0GbPjrzTpXGURmbMN3zdU2jmpTL2MOgdMz7iDMKuranba1G63AwYTgR8/YSCRcfpEQm7e1Kc0ITvmpCDDs5U+Nv81055lIefB82Yg8=
cache: npm
script: npm run deploy
after_script: npm run alias
