const locations = [
	{
		"id": "178365",
		"spaceID": "w17836520002",
		"title": "Necessitatibus doloremque odit culpa necessitatibus repellendus excepturi sint deleniti.",
		"type": "Shed",
		"owner": "zoe57",
		"location": {
			"type": "Point",
			"coordinates": "[-77.04339054213445, 38.87820062621056]",
			"lat": "38.87820062621056",
			"lat": "-77.04339054213445",
		},
		"coverImage": "test1.jpg",
		"availability": {},
		"hourlyAvail": false,
		"dailyAvail": false,
		"monthlyAvail": false,
		"longTerm": false,
		"description": "Molestiae voluptatibus nam optio vitae cum modi. Suscipit delectus labore dignissimos ad a. Nam doloribus praesentium atque. Nobis odio eos consequatur doloribus. Accusantium consequuntur dolor perferendis corrupti. Blanditiis ipsa libero pariatur sapiente quam ab. Inventore impedit dolore veniam placeat corrupti error rem neque. Illum animi porro natus voluptas nam temporibus ipsum fuga. Soluta molestias dolor autem inventore quas. Natus optio ratione distinctio mollitia non. Suscipit illum laborum ea illum veritatis optio. Distinctio deleniti debitis provident nihil in.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": true,
			"heat": true,
			"water": false,
			"bathroom": true,
		},
	},
	{
		"id": "927752",
		"spaceID": "w92775220002",
		"title": "Illo sit molestias vel explicabo.",
		"type": "Workspace",
		"owner": "jessicaharris",
		"location": {
			"type": "Point",
			"coordinates": "[-77.00048196272972, 38.91015435663988]",
			"lat": "38.91015435663988",
			"lat": "-77.00048196272972",
		},
		"coverImage": "test2.jpg",
		"availability": {},
		"hourlyAvail": false,
		"dailyAvail": true,
		"monthlyAvail": false,
		"longTerm": false,
		"description": "Labore qui labore excepturi voluptates consequatur deserunt. Recusandae voluptatem aliquid deserunt minima magnam. Quidem quo dolor fugiat accusamus tenetur esse aut numquam. Doloribus ex perspiciatis consequatur odit laboriosam iste. Explicabo dolor similique eaque libero quos praesentium. Veniam aliquam sit fuga ratione porro voluptate. Corporis suscipit dolorem iure eius ea. Placeat voluptatibus ipsam voluptatibus deserunt praesentium quasi.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": false,
			"heat": true,
			"water": false,
			"bathroom": false,
		},
	},
	{
		"id": "432960",
		"spaceID": "f43296020002",
		"title": "Repellendus possimus animi adipisci eos voluptates occaecati.",
		"type": "Whole Garage",
		"owner": "lewisleah",
		"location": {
			"type": "Point",
			"coordinates": "[-77.07625896783793, 38.88636749261948]",
			"lat": "38.88636749261948",
			"lat": "-77.07625896783793",
		},
		"coverImage": "test3.jpg",
		"availability": {},
		"hourlyAvail": true,
		"dailyAvail": false,
		"monthlyAvail": false,
		"longTerm": true,
		"description": "Sequi molestias nisi commodi nam sit sit. Officiis quos similique velit omnis distinctio. Praesentium odit minus accusamus debitis dicta velit est. Est cumque doloribus animi. Alias repellat pariatur sapiente laboriosam velit a quas. Eos quo sapiente minus dolorem voluptates. Ea vitae ipsa at laudantium vitae eligendi quod molestiae. Deleniti dicta debitis hic tenetur neque ipsum. Sed minima numquam earum illum magni cumque. Reprehenderit consectetur tempora saepe. Aut nostrum vitae repellendus non praesentium assumenda perspiciatis. Incidunt consequatur occaecati iure facilis quis necessitatibus.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": false,
			"heat": true,
			"water": true,
			"bathroom": false,
		},
	},
	{
		"id": "640108",
		"spaceID": "g64010820002",
		"title": "Sint odio esse iste.",
		"type": "Whole Garage",
		"owner": "williamreese",
		"location": {
			"type": "Point",
			"coordinates": "[-77.10681308299677, 38.85826628093265]",
			"lat": "38.85826628093265",
			"lat": "-77.10681308299677",
		},
		"coverImage": "test4.jpg",
		"availability": {},
		"hourlyAvail": true,
		"dailyAvail": false,
		"monthlyAvail": false,
		"longTerm": false,
		"description": "Nihil earum voluptatum quaerat impedit nostrum hic. Numquam iusto adipisci eveniet. Praesentium praesentium debitis excepturi quas animi animi. Debitis fugiat quaerat velit culpa fugit. Voluptates eaque beatae dolor veritatis hic. Adipisci eum temporibus amet cumque. Repellendus soluta saepe ullam ad possimus. Dignissimos at repellendus labore. Voluptates ea perferendis rem. Corrupti consequuntur exercitationem minima autem ratione maxime ea. Libero sed possimus inventore architecto.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": true,
			"heat": false,
			"water": true,
			"bathroom": false,
		},
	},
	{
		"id": "392209",
		"spaceID": "f39220920002",
		"title": "Assumenda omnis laborum earum odio doloremque.",
		"type": "Shop",
		"owner": "larsenscott",
		"location": {
			"type": "Point",
			"coordinates": "[-77.03034298002488, 38.8566301395652]",
			"lat": "38.8566301395652",
			"lat": "-77.03034298002488",
		},
		"coverImage": "test5.jpg",
		"availability": {},
		"hourlyAvail": true,
		"dailyAvail": true,
		"monthlyAvail": false,
		"longTerm": false,
		"description": "Voluptatem eveniet nihil accusantium. Voluptatem quod quod corrupti quos excepturi distinctio assumenda. Eligendi beatae provident nulla tempora maxime asperiores. Quae quidem eius iure. Quae ullam at a quaerat sint. Eius esse iste dolores deserunt. Animi assumenda ab explicabo recusandae qui repellat. Aut corporis amet voluptatibus quos enim natus eaque. Commodi tempora saepe adipisci eius sit. Laborum aliquam quisquam tenetur repellat. Odio odio officiis inventore voluptas excepturi.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": false,
			"heat": false,
			"water": false,
			"bathroom": true,
		},
	},
	{
		"id": "428798",
		"spaceID": "w42879820002",
		"title": "Voluptatum libero perspiciatis a vitae ipsa ea.",
		"type": "Storage Facility",
		"owner": "vriley",
		"location": {
			"type": "Point",
			"coordinates": "[-77.00480491677222, 38.85938899391699]",
			"lat": "38.85938899391699",
			"lat": "-77.00480491677222",
		},
		"coverImage": "test6.jpg",
		"availability": {},
		"hourlyAvail": false,
		"dailyAvail": true,
		"monthlyAvail": true,
		"longTerm": true,
		"description": "Totam consectetur vel at necessitatibus. Dolorem perspiciatis reprehenderit eius temporibus et tenetur. Ipsa animi quas eveniet soluta. Blanditiis facilis nostrum voluptate laboriosam sunt voluptas. Consequatur reprehenderit ut porro. Beatae officiis beatae quia. Ipsum odio pariatur soluta ab eligendi neque. Sed incidunt minus molestias necessitatibus. Quaerat provident inventore at cupiditate sint. Modi cumque vero optio cumque eum neque. Voluptatem soluta eius debitis itaque nobis rem. Repellendus repellendus occaecati laborum ex dolores. Fugiat culpa in quibusdam neque dolor corrupti.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": false,
			"heat": false,
			"water": true,
			"bathroom": false,
		},
	},
	{
		"id": "396199",
		"spaceID": "p39619920002",
		"title": "Magnam laboriosam nisi facilis.",
		"type": "Whole Garage",
		"owner": "butlerandrew",
		"location": {
			"type": "Point",
			"coordinates": "[-77.05829189965911, 38.85977821157666]",
			"lat": "38.85977821157666",
			"lat": "-77.05829189965911",
		},
		"coverImage": "test7.jpg",
		"availability": {},
		"hourlyAvail": true,
		"dailyAvail": true,
		"monthlyAvail": true,
		"longTerm": false,
		"description": "Tenetur officia temporibus ab eveniet. Quasi est tenetur pariatur voluptatum quos. Quos ipsa quo eius fugiat nihil. Doloremque voluptates eos est voluptatem nisi. Perferendis harum quis corrupti voluptate iusto. At perspiciatis numquam omnis fugit illo. Beatae recusandae hic vero odit laborum distinctio. Explicabo facere at facere iure. Tempore accusantium ad sunt at corrupti recusandae numquam. Praesentium quas voluptatem aspernatur aut vero nemo voluptate repudiandae. Quis libero quia impedit libero distinctio optio nihil reiciendis.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": true,
			"heat": false,
			"water": false,
			"bathroom": true,
		},
	},
	{
		"id": "699806",
		"spaceID": "f69980620002",
		"title": "Fuga labore occaecati ducimus unde sequi vitae perferendis.",
		"type": "Storage Facility",
		"owner": "petersenwilliam",
		"location": {
			"type": "Point",
			"coordinates": "[-77.03619988334454, 38.908881440547496]",
			"lat": "38.908881440547496",
			"lat": "-77.03619988334454",
		},
		"coverImage": "test8.jpg",
		"availability": {},
		"hourlyAvail": false,
		"dailyAvail": false,
		"monthlyAvail": true,
		"longTerm": true,
		"description": "Illo repudiandae deserunt dignissimos exercitationem temporibus impedit. Sapiente nihil dolor provident eligendi eveniet quo neque. Libero impedit totam ducimus dolore quia. Consequuntur ipsa possimus distinctio sint maxime. Velit omnis amet officia delectus et aliquid recusandae praesentium. Dolorum ad dignissimos aliquid temporibus placeat error. Distinctio beatae architecto est ullam. Deleniti in repellendus id dolorum magnam vero. Excepturi soluta neque perferendis. Quasi minus ratione quos itaque omnis esse omnis expedita.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": false,
			"heat": false,
			"water": false,
			"bathroom": true,
		},
	},
	{
		"id": "419541",
		"spaceID": "g41954120002",
		"title": "Corporis ratione nobis quidem tempora praesentium placeat enim.",
		"type": "Storage Facility",
		"owner": "ramoslindsey",
		"location": {
			"type": "Point",
			"coordinates": "[-77.04914929022912, 38.887618204649726]",
			"lat": "38.887618204649726",
			"lat": "-77.04914929022912",
		},
		"coverImage": "test9.jpg",
		"availability": {},
		"hourlyAvail": false,
		"dailyAvail": false,
		"monthlyAvail": true,
		"longTerm": true,
		"description": "Consequuntur consequatur est delectus officiis. Dignissimos ipsa harum magni omnis praesentium ab. Deleniti est quo sint molestias inventore illo dicta. A quidem magni praesentium eos distinctio. Voluptas consequatur libero sequi. Iste sunt optio adipisci ipsam molestiae id. Quis porro aut odit nesciunt esse. Iure dicta repellat recusandae error cum porro hic. Voluptatem deserunt fugit sequi atque a. Aspernatur incidunt iste voluptate ea. Expedita debitis ipsa mollitia a. Blanditiis accusamus provident quasi aspernatur explicabo.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": false,
			"heat": true,
			"water": true,
			"bathroom": false,
		},
	},
	{
		"id": "156192",
		"spaceID": "g15619220002",
		"title": "Ipsum sequi nobis nostrum temporibus perspiciatis.",
		"type": "Storage Facility",
		"owner": "alan20",
		"location": {
			"type": "Point",
			"coordinates": "[-77.03336874968217, 38.97762568891165]",
			"lat": "38.97762568891165",
			"lat": "-77.03336874968217",
		},
		"coverImage": "test10.jpg",
		"availability": {},
		"hourlyAvail": false,
		"dailyAvail": false,
		"monthlyAvail": true,
		"longTerm": false,
		"description": "Ab dolorum porro inventore laboriosam quaerat. Blanditiis incidunt facere aperiam animi rem explicabo. Sit nulla quibusdam veniam reiciendis possimus quia molestiae. Excepturi labore quas tempore quia error placeat velit. Non dolores cum excepturi fuga. Deserunt modi iste eius provident. Harum odit adipisci soluta itaque fuga. Eaque laboriosam possimus aliquid molestiae sapiente fugit.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": true,
			"heat": true,
			"water": false,
			"bathroom": false,
		},
	},
	{
		"id": "798838",
		"spaceID": "w79883820002",
		"title": "Maxime ipsum optio est ducimus corporis consequatur eum.",
		"type": "Shop",
		"owner": "alvarezchad",
		"location": {
			"type": "Point",
			"coordinates": "[-76.9967613507232, 38.97215992044375]",
			"lat": "38.97215992044375",
			"lat": "-76.9967613507232",
		},
		"coverImage": "test11.jpg",
		"availability": {},
		"hourlyAvail": true,
		"dailyAvail": true,
		"monthlyAvail": true,
		"longTerm": false,
		"description": "Impedit provident cum eius quidem necessitatibus. Nemo delectus molestias dolorem corrupti consectetur labore laborum qui. Consequatur harum sunt suscipit commodi. Quas magni nemo amet explicabo quas amet enim. Illo autem repudiandae assumenda sunt odio. Aliquam illum similique iste. Perspiciatis laboriosam mollitia ad quibusdam. Consequatur doloremque doloremque commodi similique cum necessitatibus. Dolore quod tempora fugit ullam cum. Perspiciatis molestias magnam ea dolorem quae pariatur quos. Libero earum aut corporis. Quisquam id reiciendis temporibus voluptatem.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": false,
			"heat": true,
			"water": true,
			"bathroom": true,
		},
	},
	{
		"id": "923650",
		"spaceID": "w92365020002",
		"title": "Totam sed voluptate debitis doloribus.",
		"type": "Workspace",
		"owner": "phillipscharles",
		"location": {
			"type": "Point",
			"coordinates": "[-77.10610160134385, 38.95907943403968]",
			"lat": "38.95907943403968",
			"lat": "-77.10610160134385",
		},
		"coverImage": "test12.jpg",
		"availability": {},
		"hourlyAvail": true,
		"dailyAvail": false,
		"monthlyAvail": true,
		"longTerm": false,
		"description": "Iste quae explicabo eius nostrum voluptatibus unde culpa minima. Maxime repudiandae ea natus accusamus repellat aperiam. Nemo aspernatur neque assumenda laboriosam. Incidunt ex corrupti iusto fuga reiciendis quibusdam culpa aperiam. Eum beatae optio occaecati. Neque facere magni totam voluptas aliquam quasi. Aliquid occaecati labore vitae consectetur ex. Impedit illum quo est impedit facilis neque tempore.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": true,
			"heat": false,
			"water": false,
			"bathroom": true,
		},
	},
	{
		"id": "963747",
		"spaceID": "g96374720002",
		"title": "Corrupti iusto rerum nemo.",
		"type": "Shop",
		"owner": "schmittdale",
		"location": {
			"type": "Point",
			"coordinates": "[-77.04911500264213, 38.826395913413755]",
			"lat": "38.826395913413755",
			"lat": "-77.04911500264213",
		},
		"coverImage": "test13.jpg",
		"availability": {},
		"hourlyAvail": false,
		"dailyAvail": true,
		"monthlyAvail": false,
		"longTerm": false,
		"description": "Vero nostrum enim aperiam ab sequi. Commodi ad repudiandae natus doloremque nemo. Aut rerum libero hic quo earum. Sapiente perspiciatis a doloribus beatae reiciendis qui. Labore asperiores consectetur error. Vero itaque voluptatem numquam consequatur veniam. Facere nihil sit iure. Quae eius aliquam quidem modi fugit aliquam. Possimus quisquam eaque illo laudantium repellat consequatur cupiditate. Fugit deleniti quo veritatis quibusdam. Quidem aliquid fugiat facilis praesentium.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": true,
			"heat": false,
			"water": false,
			"bathroom": false,
		},
	},
	{
		"id": "303092",
		"spaceID": "w30309220002",
		"title": "Dicta est ut natus molestias temporibus.",
		"type": "Shop",
		"owner": "karen08",
		"location": {
			"type": "Point",
			"coordinates": "[-77.00788174349591, 38.888175584217976]",
			"lat": "38.888175584217976",
			"lat": "-77.00788174349591",
		},
		"coverImage": "test14.jpg",
		"availability": {},
		"hourlyAvail": false,
		"dailyAvail": true,
		"monthlyAvail": true,
		"longTerm": true,
		"description": "Recusandae vero doloremque veritatis fugit illo saepe hic. Inventore dolores voluptatibus occaecati culpa. Maiores reiciendis dolorem inventore voluptatem temporibus omnis ducimus. Sapiente neque nemo suscipit ipsam ipsum soluta voluptas. Adipisci pariatur officiis assumenda facilis deleniti. Suscipit autem perspiciatis doloribus quo. Reprehenderit placeat nesciunt ipsam tempore laboriosam quaerat. A temporibus ex fuga sapiente sint. Quisquam dolorem nihil sed maiores assumenda sit velit. Ut omnis eaque officia. Quod officia ipsam perferendis error nesciunt optio aspernatur.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": true,
			"heat": false,
			"water": false,
			"bathroom": false,
		},
	},
	{
		"id": "577339",
		"spaceID": "f57733920002",
		"title": "Explicabo rerum inventore alias veritatis unde exercitationem eaque.",
		"type": "Shed",
		"owner": "ybaker",
		"location": {
			"type": "Point",
			"coordinates": "[-77.00379191311255, 38.90398556473833]",
			"lat": "38.90398556473833",
			"lat": "-77.00379191311255",
		},
		"coverImage": "test15.jpg",
		"availability": {},
		"hourlyAvail": true,
		"dailyAvail": false,
		"monthlyAvail": true,
		"longTerm": false,
		"description": "Saepe officia voluptatem facilis autem. Fuga maxime iure dolores cupiditate. Laudantium nulla nemo maiores voluptates eaque fugiat. Cupiditate reprehenderit sed voluptates laboriosam dolores explicabo temporibus. Doloribus itaque sequi eligendi inventore explicabo odio perferendis. Labore sapiente in nam deleniti laborum. Similique odit sapiente minus sed aliquam libero. Officiis quos laboriosam illo eos voluptatibus. Sed at enim perferendis magnam alias. Vitae quisquam neque ipsa debitis illo pariatur.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": false,
			"heat": true,
			"water": true,
			"bathroom": true,
		},
	},
	{
		"id": "530207",
		"spaceID": "w53020720002",
		"title": "Quia mollitia possimus rem porro.",
		"type": "Shed",
		"owner": "wcollins",
		"location": {
			"type": "Point",
			"coordinates": "[-76.96709442361932, 38.85728076604887]",
			"lat": "38.85728076604887",
			"lat": "-76.96709442361932",
		},
		"coverImage": "test16.jpg",
		"availability": {},
		"hourlyAvail": false,
		"dailyAvail": false,
		"monthlyAvail": false,
		"longTerm": false,
		"description": "Ea corporis modi accusamus hic pariatur error voluptatibus consequatur. Animi consectetur ipsum quia. Id laudantium ut occaecati in. Error sed sapiente sit doloribus expedita eos qui. Numquam alias distinctio nam necessitatibus sunt perferendis nostrum. Expedita est consequuntur commodi ut architecto. Molestias soluta ab corrupti ea doloribus omnis sunt. Nemo asperiores eligendi libero odio esse accusantium. Temporibus consequatur aperiam est magni et aliquid eaque.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": true,
			"heat": false,
			"water": true,
			"bathroom": true,
		},
	},
	{
		"id": "541507",
		"spaceID": "w54150720002",
		"title": "Velit atque consequatur ea alias blanditiis.",
		"type": "Partial Garage",
		"owner": "georgelisa",
		"location": {
			"type": "Point",
			"coordinates": "[-77.06414925791486, 38.83610741592234]",
			"lat": "38.83610741592234",
			"lat": "-77.06414925791486",
		},
		"coverImage": "test17.jpg",
		"availability": {},
		"hourlyAvail": false,
		"dailyAvail": true,
		"monthlyAvail": true,
		"longTerm": false,
		"description": "Vero vitae est aut laudantium nesciunt dicta. Repudiandae dolore numquam velit assumenda tempora fuga suscipit. Occaecati hic quam ab. Vel exercitationem quibusdam cupiditate maxime recusandae. Totam occaecati recusandae fuga molestiae optio. Iure eaque vero animi mollitia. Modi provident ex laudantium odit.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": false,
			"heat": true,
			"water": false,
			"bathroom": true,
		},
	},
	{
		"id": "840420",
		"spaceID": "p84042020002",
		"title": "Voluptas consectetur amet corrupti exercitationem a voluptate aperiam.",
		"type": "Whole Garage",
		"owner": "christopherzimmerman",
		"location": {
			"type": "Point",
			"coordinates": "[-77.03027174895571, 38.94273339335941]",
			"lat": "38.94273339335941",
			"lat": "-77.03027174895571",
		},
		"coverImage": "test18.jpg",
		"availability": {},
		"hourlyAvail": true,
		"dailyAvail": true,
		"monthlyAvail": false,
		"longTerm": true,
		"description": "Quaerat quis tempore sed. Nesciunt officia ratione modi est atque laborum beatae. Ducimus ullam quod fugit voluptas. Excepturi eum voluptates laborum sit natus cupiditate odit. Hic occaecati reiciendis cum debitis aspernatur maiores. Doloremque odit minus quas vitae possimus quaerat. Quas magni nobis consequatur asperiores vitae neque porro. Numquam aliquam velit repudiandae quia. Aliquam aperiam dolore dolorem quidem qui doloremque molestias ratione. Autem expedita numquam nulla molestiae.",
		"street": "123 Main",
		"city": "Washington",
		"state": "DC",
		"zip": 20002,
		"amenities": {
			"electricity": false,
			"heat": true,
			"water": false,
			"bathroom": true,
		},
	},
]

const userStatus = {
	username: '',
	loggedIn: true
}

const demoUser = {
	'demo@example.com': 'password'
}

module.exports = {locations, userStatus, demoUser}